### ISSUE TITLE
lsof on busybox

### ISSUE THREAD

**Issue by jbauernbergerCDE** [zevv/lsofgraph#12]
Hi,
thanks for this tool I love it on amd86 where lsof is a standalone command. It seems this will not work when [lsof is part of busybox](https://github.com/brgl/busybox/blob/master/procps/lsof.c) because the -F option output will look like:

```
1	/usr/lib/systemd/systemd	/dev/null
1	/usr/lib/systemd/systemd	/dev/null
1	/usr/lib/systemd/systemd	/dev/null
1	/usr/lib/systemd/systemd	/dev/kmsg
1	/usr/lib/systemd/systemd	anon_inode:[eventpoll]
1	/usr/lib/systemd/systemd	anon_inode:[signalfd]
1	/usr/lib/systemd/systemd	anon_inode:inotify
1	/usr/lib/systemd/systemd	/sys/fs/cgroup
1	/usr/lib/systemd/systemd	anon_inode:[timerfd]
1	/usr/lib/systemd/systemd	anon_inode:[eventpoll]
```

thanks!

**Comment by zevv** [comment]
yeah, that's a pity, sorry to hear that doesn't work for you on busybox.

I don't think I want to spend the time and effort to make this work however, since it's busybox that generates the "wrong" output here, although the format is not officially specified of course, so busybox is free to emit whatever it likes.

If anyone comes up with a patch to handle this, I'd be glad to merge!
